# Generated by Django 4.2.7 on 2023-11-24 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promptai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
