site_name: Cours de développement en Python
site_url: https://yostane.github.io/cours-python/
repo_url: https://github.com/yostane/cours-python
repo_name: yostane/cours-python
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yostane

nav:
  - Introduction: index.md
  - Tour du langage: python-tour.md
  - Exercices: python-exercices.md
  - POO: python-poo.md
  - Exercices POO: python-poo-exercices.md
  - Porgrammtion fonctionnelle: python-func.md
  - Exercices Prog fonctionnelle: python-func-exercices.md
  - Django: django-tour.md
  - Exemples de projets: projects-type.md

plugins:
  - search
  - glightbox

theme:
  logo: img/logo.png
  favicon: img/logo.png
  name: material
  features:
    - navigation.top
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: cyan
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: lime
      accent: green

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: ["includes", "material/tour", "material/poo"]
      auto_append:
        - "includes/abbreviations.md"
