# Generated by Django 5.1.2 on 2024-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pakiman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
